### ISSUE TITLE
Inverter Board PinOut

### ISSUE THREAD

**Issue by on4ip** [damienmaguire/Nissan-Leaf-Inverter-Controller#3]
Hi.Thx for grate work. I have leaf inverter AZ0 and looking custom board to replace inverter board.
I want to know standart pinout of inverter board with PWM signal and current signals, but in ur documets Inverter board pinout looks like connection to VCU. Is it correct?

**Comment by damienmaguire** [comment]
Please use the support thread on the Openinverter Forum for technical questions :
https://openinverter.org/forum/viewtopic.php?f=4&t=179
